### ISSUE TITLE
`file` dependency missing

### ISSUE THREAD

**Issue by simeoncarstens** [GuillaumeDesforges/fix-python#1]
When running `fix-python` following the instructions in the README file on a simple example, it errors out:
```console
$ fix-python --venv .venv/ --libs .nix/libs.nix
Automatically adding "file" to PATH.
Automatically adding "patchelf" to PATH.
sh: line 1: file: command not found
sh: line 1: file: command not found
sh: line 1: file: command not found
sh: line 1: file: command not found
sh: line 1: file: command not found
sh: line 1: file: command not found
Found 1 binary files
Patching file: 
patchelf: getting info about '': No such file or directory
patchelf: getting info about '': No such file or directory
patchelf: getting info about '': No such file or directory
```
Reproduce it as follows:
```console
$ python -m venv .venv --copies
$ mkdir .nix && echo "[]" > .nix/libs.nix
$ nix shell github:guillaumedesforges/fix-python
$ fix-python --venv .venv/ --libs .nix/libs.nix
< output above >
```
As @GuillaumeDesforges pointed out to me offline, replacing the Nix shell incantation by `nix shell nixpkgs#file github:guillaumedesforges/fix-python` makes `fix-python` run correctly, but better to fix this in `fix-python` itself.

Other than that, big thanks for this super useful tool! Worked (apart from the above) perfectly for me and will be a literal life-saver :100:

**Comment by denismaciel** [comment]
Had the same problem... It would be great to have that integrated into the solution so it "just work™"

Thanks for the soltuion btw... It was the only piece of software that was missing for me to do the jump to NixOS. Hopefully, won't ever need to use Ubuntu again. Cheers!

**Comment by GuillaumeDesforges** [comment]
Thanks for the great word, I appreciate it!

The fix is embarassing so I'll let you check the commit itself. :sweat_smile: 
Cheers

**Comment by simeoncarstens** [comment]
I'm confused what happened here - it is not fixed, right? In any case, I put up a PR for this (#4).

**Comment by simeoncarstens** [comment]
Ah - so it is fixed, directly on `master` :slightly_smiling_face: feel free to close #4 then.
