### ISSUE TITLE
Run the fix automatically after every `pip install`

### ISSUE THREAD

**Issue by MathieuMoalic** [GuillaumeDesforges/fix-python#14]
I was wondering if there is a convenient way to run this script any time a new library is installed?
Given a somewhat basic flake.nix that sets up a python environment:
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = {
    nixpkgs,
    flake-utils,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (
      system: let
        pkgs = import nixpkgs {inherit system;};
        devEnv = pkgs.mkShell {
          buildInputs = with pkgs; [
            python311
            python311Packages.pip
            python311Packages.virtualenv
            pythonManylinuxPackages.manylinux2014Package
            cmake
            ninja
            gcc
            pre-commit
          ];

          shellHook = ''
            set -euo pipefail
            test -d .venv || (${pkgs.python3.interpreter} -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt)
            source .venv/bin/activate
          '';
        };
      in {
        devShell = devEnv;
      }
    );
}
```
How could one achieve that? I was thinking to add a wrapper around `pip install` a bit like:
```bash 
pip() {
  command pip "$@"
  if [[ "$1" == "install" ]]; then
    nix run github:GuillaumeDesforges/fix-python -- --venv .venv
  fi
}
```
but this couldn't be in shellHooks as `nix develop` start a new shell. 
I think this would be the last step to make python "just work" on NixOS. Maybe even a declarative way to do it would be better but I am not sure this would be easy to do. Any thoughts?

**Comment by GuillaumeDesforges** [comment]
Hey @MathieuMoalic !

It's a tough one. My honest feeling is that `fix-python` should focus on exactly what it does, and it's up to the user to compose with this tool to build more complex behavior (à la GNU).
I think the wrapper is a nice idea.

I'm closing this issue, but feel free to continue the discussion and post more solutions. :slightly_smiling_face:
