### ISSUE TITLE
Can we make a list of default libraries to patch?

### ISSUE THREAD

**Issue by simeoncarstens** [GuillaumeDesforges/fix-python#3]
The README says of `pkgs.gcc.cc`, `pkgs.glibc`, and `pkgs.zlib` that 
> [...] these three packages are fundamental for most Python packages and should never me removed.

Would patching them by default make sense, so an occasional user doesn't have to jump through the hoops of creating `.nix/libs.nix` and specifying the CLI argument? If so, I'd be happy to prepare a PR :slightly_smiling_face:

**Comment by GuillaumeDesforges** [comment]
Thanks for the suggestion. It makes a lot of sense, I would welcome such a PR!

Just in case, I would need this feature to be enabled/disabled by a CLI argument.

**Comment by simeoncarstens** [comment]
Closed via #5.
