### ISSUE TITLE
darwin?

### ISSUE THREAD

**Issue by timsears** [GuillaumeDesforges/fix-python#7]
Doesn't seem to work for darwin. Is darwin possible?

**Comment by GuillaumeDesforges** [comment]
Hi! I have not tested with Darwin, only Linux.

This tool is primarily meant to help NixOS users run arbitrary binaries from Python packages that have not been packaged using Nix (e.g. wheels with pre-compiled binaries). AFAIK, NixOS is only Linux.

I'm curious to know how exactly you tried to use `fix-python` on darwin, and why?

**Comment by GuillaumeDesforges** [comment]
Closing as stale. Feel free to re-open with additional information.
