### ISSUE TITLE
patchelf error

### ISSUE THREAD

**Issue by TJesionowski** [GuillaumeDesforges/fix-python#8]
I followed the instructions on the readme and it says this for every (or almost every?) file.
```
Patching file: /home/.../.venv/lib/python3.12/site-packages/....so
patchelf: cannot find section '.interp'. The input file is most likely statically linked
```
I'm not sure if that broke anything important, but the packages worked and pip stopped working after I ran your command.

**Comment by GuillaumeDesforges** [comment]
Hi @TJesionowski ! Thanks for the report. :slightly_smiling_face: 

This line is a warning and results in a no-op, meaning it does not affect the file.
You can safely ignore this.

However pip should still work after running the script.
Could you please share more details about your OS, the version of Python, how you created the venv and the version of pip?

**Comment by GuillaumeDesforges** [comment]
Closing as stale
