### ISSUE TITLE
After `fix-python`, `torch` can't find `libstdc++.so.6`

### ISSUE THREAD

**Issue by meditans** [GuillaumeDesforges/fix-python#9]
Thank you for this library. I tried all python solutions for nixos and they all fail in one way or another when trying to reproduce modern machine learning project with multiple pieces. Therefore I am very interested in trying this relatively simple solution of just using `poetry` for python management and patching the venv.

Here's a simple setup: poetry is installed at the system level, in a folder I have a `pyproject.toml` containing:
```
[tool.poetry]
name = "00-fix-python+poetry"
version = "0.1.0"
description = ""
authors = ["AB <ab@c.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

and a custom `libs.nix` file like it's suggested in the readme:
```
let pkgs = import (builtins.getFlake "nixpkgs") { };
in [ pkgs.stdenv.cc.cc.lib pkgs.gcc.cc pkgs.glibc pkgs.zlib ]
```
you can see I added `stdenv.cc.cc.lib` because that's the location of `libstdc++.so.6` normally.

Then I patch the venv with:
```
$ fix-python --venv /home/carlo/system/cache/pypoetry/virtualenvs/00-fix-python+poetry-f40ciUoz-py3.11 --libs ./libs.nix
```
But when I execute `poetry run python` and `import torch` I don't have `libstdc++.so.6`:
```
$ poetry run python
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carlo/system/cache/pypoetry/virtualenvs/00-fix-python+poetry-f40ciUoz-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/home/carlo/system/cache/pypoetry/virtualenvs/00-fix-python+poetry-f40ciUoz-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 195, in _load_global_deps
    raise err
  File "/home/carlo/system/cache/pypoetry/virtualenvs/00-fix-python+poetry-f40ciUoz-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

How do you think I could debug and avoid this problem?

**Comment by meditans** [comment]
It seems that this is linked to the `libtorch_global_deps.so` file, [see this on the nixos discourse](https://discuss.pytorch.org/t/pytorch-cannot-open-libstdc-so-6/99825), but I find interesing that for almost all the torch files in the venv, I find a patchelf warning like:
```
Patching file: /home/carlo/system/cache/pypoetry/virtualenvs/00-fix-python+poetry-f40ciUoz-py3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.so
patchelf: cannot find section '.interp'. The input file is most likely statically linked
```

I also found a [nix solution for this problem](https://github.com/eth-sri/lmql/blob/main/scripts/flake.d/overrides.nix#L28-L40) in a proper packaging of `lmql`.

**Comment by meditans** [comment]
In the end I solved the problem just adding the gcc lib dependency in my `libtorch_global_deps.so` in the poetry venv.
```
patchelf --add-rpath /nix/store/9r8z1qr5jhv90fl2457qqml7qgk88fd6-gcc-13.2.0-lib/lib --add-needed libstdc++.so libtorch_global_deps.so
```
I think this process should be automated and put in the `fix-python` script itself. I'm not sure on the best ui for this, maybe a flag like `--fix-torch-libstdc++`, or a `--fix-torch` umbrella flag that applies all the patches that are needed for torch?

I'm curious about your ideas here, I can also prepare a PR if you want once we finalize the design.

**Comment by GuillaumeDesforges** [comment]
Thank you very much for the detailed report! Seems like torch does something weird again. :cry: 

The `--fix-torch` sounds nice to me! I would very much welcome such a contribution. :100:

**Comment by eloycoto** [comment]
@GuillaumeDesforges I added the following line at the end, are you ok if I send the PR

```
torch_files=$(find "$(realpath "$VENV_PATH")" -name libtorch_global_deps.so)
cat <<< "$torch_files" \
  | while read -r file
    do
      echo "Patching torch file: $file"
      patchelf $file --add-needed libstdc++.so
    done
```
